# CHANGED FROM SCANNER VERSION
# -> screen distance (196 -> 210)
# -> simulate = True, scanner_synch False
# -> Remove top ups

preferences:
    general:
        audioLib: SoundDevice
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True
    screen: 0

monitor:
    name: default
    width: 69  # in cm
    distance: 210 
    gamma: 2.1

operating system: mac # specify the OS the code is run on as 'mac', 'linux', or 'windows'

mouse:
    visible: False

eyetracker:
    model: eyelink
    address: '100.1.1.1'
    dot_size: 0.1  # in deg
    options: # Eyelink specific settings
        active_eye: left  # [right]
        calibration_type: HV5  # [H3, HV3, HV5, HV9], # Jurjen = HV5
        sample_rate: 1000
        calibration_area_proportion: 0.4 0.4
        validation_area_proportion: 0.4 0.4                

mri:
    TR: 0.5  # seconds between volume acquisitions
    topup_scan: True
    topup_duration: 0 # topup scan duration in seconds (no 't's)

stim_settings:
    scanner_sync: True                # set this to true to make bar move on input 't'
    screenshot: True
    squares_in_bar: 2
    bar_pass_steps: 20                # number of steps the bar takes to traverse the aperture
    blanks_length: 10                  # length of interbar periods (-1 in orientation). like bar pass steps, in units of TRs or bar step length
    bar_step_length : .5         # in seconds, should match TR if scanner_sync is True
    bar_orientations: [-1, 225, 315, -1,  45, 135,  -1, -1]
    bar_width_in_degrees: 1.25
    checkers_motion_speed: 3          # checkers motion speed. direction is randomly up/down at each bar step
    size_fixation_dot_in_degrees: 0.05 # dot changes color on average every two TRs (or bar steps)
    fixation_method : cross  
    fix_cross_parameters:
        dot_radius: 0.05
        line_width: 5 #0.025 # *101.6

        

task_settings: 
    response_interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
    color_switch_interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 
